spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: music-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true